#!/usr/bin/env bash
# agents-md.sh [--check] [--force] [--repo <dir>] — generates <repo>/AGENTS.md
# for OpenAI Codex from the repository's Claude rules, so both agents follow
# the same project rules. Codex reads only AGENTS.md files (no CLAUDE.md, no
# imports, no path-scoped rules, 32 KiB default cap project_doc_max_bytes);
# the single source stays CLAUDE.md + .claude/rules/**.
#
# Output, in order:
#   1. the GENERATED header line;
#   2. the repo CLAUDE.md, each "@path" import line replaced by the file's
#      content when it is an always-on .claude/rules file, else by
#      "read `<path>`";
#   3. every always-on rule (a .claude/rules/**/*.md without "paths:"
#      frontmatter) not already imported, under "## <path>", frontmatter
#      stripped, root-level files first, then by path (C collation);
#   4. "## Scoped rules": a "| when you touch | read |" table, one row per rule
#      file with "paths:" frontmatter (Codex runs from the repo root, so a
#      nested AGENTS.md per app would not load);
#   5. the OpenRig managed blocks of the previous AGENTS.md
#      (<!-- BEGIN OpenRig MANAGED BLOCK: <id> --> … END …), verbatim, in
#      their original order.
# Over 32768 bytes the always-on rules switch to pointer mode (a list of files
# to read before any change) and a warning naming the size goes to stderr.
# The output is deterministic: the same input gives a byte-identical file.
#
# --check   no write; exit 1 with one line when AGENTS.md is missing or differs
#           from the generated content (OpenRig managed blocks ignored).
# --force   overwrite an AGENTS.md that lacks the GENERATED header.
# --repo    the repository root, default: the git toplevel of the cwd.
# Exit: 0 written / up to date, 1 error or --check mismatch, 2 hand-written
# AGENTS.md refused (no --force). Prints "AGENTS.md" on stdout when written.
# Requires yq (mikefarah v4) for the frontmatter.
set -euo pipefail

# shellcheck source=../hooks/lib.sh
source "$(dirname "${BASH_SOURCE[0]}")/../hooks/lib.sh"

HEADER='<!-- GENERATED by claude-conventions agents-md.sh from CLAUDE.md and .claude/rules/** — edit those, then rerun. Do not edit by hand. -->'
MAX_BYTES=32768

usage() {
  printf 'usage: agents-md.sh [--check] [--force] [--repo <dir>]\n' >&2
  exit 1
}

check=0
force=0
repo=""
while [ "$#" -gt 0 ]; do
  case "$1" in
    --check)
      check=1
      shift
      ;;
    --force)
      force=1
      shift
      ;;
    --repo)
      if [ "$#" -lt 2 ]; then
        usage
      fi
      repo="$2"
      shift 2
      ;;
    *) usage ;;
  esac
done

if ! has_mikefarah_yq; then
  printf 'agents-md: yq (mikefarah v4) is required — %s\n' "$(yq_install_hint)" >&2
  exit 1
fi

if [ -z "$repo" ]; then
  if ! in_git_repo .; then
    printf 'agents-md: not inside a git repository — pass --repo <dir>\n' >&2
    exit 1
  fi
  repo="$(git rev-parse --show-toplevel)"
fi
if [ ! -d "$repo" ]; then
  printf 'agents-md: repository not found: %s\n' "$repo" >&2
  exit 1
fi
root="$(cd "$repo" && pwd -P)"
target="$root/AGENTS.md"

WORK="$(mktemp -d)"
trap 'find "$WORK" -depth -delete' EXIT

# ---------------------------------------------------------------------------
# Rule files
# ---------------------------------------------------------------------------

# has_frontmatter <file> — true when the first line is "---" and a closing
# "---" line follows.
has_frontmatter() {
  awk 'NR == 1 { if ($0 != "---") { exit 1 }; next } $0 == "---" { found = 1; exit } END { exit !found }' "$1"
}

# rule_paths <file> — prints the "paths:" globs of the frontmatter, one per
# line (a single string counts as one glob); nothing for an always-on file.
rule_paths() {
  if ! has_frontmatter "$1"; then
    return 0
  fi
  if ! yq --front-matter=extract '[.paths // []] | flatten | .[]' "$1" 2>"$WORK/yq.err"; then
    printf 'agents-md: invalid frontmatter in %s: %s\n' "${1#"$root/"}" "$(head -n 1 "$WORK/yq.err")" >&2
    exit 1
  fi
}

# rule_body <file> — prints the file without its frontmatter and without the
# blank lines that open or close it, ending with one newline.
rule_body() {
  local file="$1"
  {
    if has_frontmatter "$file"; then
      awk 'NR == 1 { next } !closed && $0 == "---" { closed = 1; next } closed { print }' "$file"
    else
      cat "$file"
    fi
  } | awk '
    NF { started = 1 }
    !started { next }
    !NF { blanks++; next }
    { while (blanks > 0) { print ""; blanks-- } print }'
}

# Every rule file, repo-relative, root-level first, then by path.
: >"$WORK/always-on"
: >"$WORK/scoped"
if [ -d "$root/.claude/rules" ]; then
  find -L "$root/.claude/rules" -type f -name '*.md' \
    | while IFS= read -r path; do
      rel="${path#"$root/"}"
      sub="${rel#.claude/rules/}"
      depth=0
      if [ "$sub" != "${sub#*/}" ]; then
        depth=1
      fi
      printf '%s\t%s\n' "$depth" "$rel"
    done \
    | LC_ALL=C sort -t "$(printf '\t')" -k1,1 -k2,2 \
    | cut -f2 >"$WORK/rules"
  while IFS= read -r rel; do
    rule_paths "$root/$rel" >"$WORK/globs"
    if [ -s "$WORK/globs" ]; then
      globs=""
      while IFS= read -r glob; do
        if [ -n "$globs" ]; then
          globs="$globs, "
        fi
        globs="$globs\`$glob\`"
      done <"$WORK/globs"
      printf '%s\t%s\n' "$rel" "$globs" >>"$WORK/scoped"
    else
      printf '%s\n' "$rel" >>"$WORK/always-on"
    fi
  done <"$WORK/rules"
fi

# is_always_on <rel> — true when <rel> is a listed always-on rule file.
is_always_on() {
  grep -qxF -- "$1" "$WORK/always-on"
}

# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------

# render_claude_md <mode> — prints CLAUDE.md with its import lines resolved
# (mode inline: always-on rules inlined; mode pointer: every import becomes a
# pointer) and records the inlined files in $WORK/imported.
render_claude_md() {
  local mode="$1" line path
  : >"$WORK/imported"
  if [ ! -f "$root/CLAUDE.md" ]; then
    return 0
  fi
  while IFS= read -r line || [ -n "$line" ]; do
    if [[ "$line" =~ ^@([^[:space:]]+)[[:space:]]*$ ]]; then
      path="${BASH_REMATCH[1]}"
      path="${path#./}"
      if is_always_on "$path"; then
        printf '%s\n' "$path" >>"$WORK/imported"
        if [ "$mode" = "inline" ]; then
          rule_body "$root/$path"
          continue
        fi
      fi
      # shellcheck disable=SC2016  # literal Markdown backticks, not an expansion
      printf 'read `%s`\n' "$path"
      continue
    fi
    printf '%s\n' "$line"
  done <"$root/CLAUDE.md"
}

# render_always_on <mode> — prints the always-on rules not imported by
# CLAUDE.md: inlined under "## <path>", or as one pointer list.
render_always_on() {
  local mode="$1" rel listed=0
  while IFS= read -r rel; do
    if grep -qxF -- "$rel" "$WORK/imported"; then
      continue
    fi
    if [ "$mode" = "inline" ]; then
      printf '\n## %s\n\n' "$rel"
      rule_body "$root/$rel"
      continue
    fi
    if [ "$listed" -eq 0 ]; then
      printf '\n## Always-on rules\n\nRead these files before any change:\n\n'
      listed=1
    fi
    # shellcheck disable=SC2016  # literal Markdown backticks, not an expansion
    printf -- '- `%s`\n' "$rel"
  done <"$WORK/always-on"
}

# render_scoped — prints the "## Scoped rules" table, nothing without scoped rules.
render_scoped() {
  local rel globs
  if [ ! -s "$WORK/scoped" ]; then
    return 0
  fi
  printf '\n## Scoped rules\n\nBefore touching a file matching a glob, read the rule file of its row.\n\n'
  printf '| when you touch | read |\n|---|---|\n'
  while IFS="$(printf '\t')" read -r rel globs; do
    # shellcheck disable=SC2016  # literal Markdown backticks, not an expansion
    printf '| %s | `%s` |\n' "$globs" "$rel"
  done <"$WORK/scoped"
}

# managed_blocks <file> — prints every OpenRig managed block of <file>
# verbatim, in file order, separated by one blank line.
managed_blocks() {
  awk '
    !inside && /^<!-- BEGIN OpenRig MANAGED BLOCK: [^ ]+ -->$/ {
      id = $0
      sub(/^<!-- BEGIN OpenRig MANAGED BLOCK: /, "", id)
      sub(/ -->$/, "", id)
      if (count++) { print "" }
      inside = 1
    }
    inside { print }
    inside && $0 == "<!-- END OpenRig MANAGED BLOCK: " id " -->" { inside = 0 }
  ' "$1"
}

# without_managed_blocks <file> — prints <file> without its managed blocks,
# runs of blank lines squeezed to one and trailing blank lines dropped, so
# two files compare on their generated text only.
without_managed_blocks() {
  awk '
    !inside && /^<!-- BEGIN OpenRig MANAGED BLOCK: [^ ]+ -->$/ {
      id = $0
      sub(/^<!-- BEGIN OpenRig MANAGED BLOCK: /, "", id)
      sub(/ -->$/, "", id)
      inside = 1
      next
    }
    inside {
      if ($0 == "<!-- END OpenRig MANAGED BLOCK: " id " -->") { inside = 0 }
      next
    }
    !NF { blanks = 1; next }
    { if (blanks && printed) { print "" } blanks = 0; printed = 1; print }
  ' "$1"
}

# render <mode> — prints the whole AGENTS.md for <mode> (inline / pointer).
render() {
  local mode="$1"
  printf '%s\n' "$HEADER"
  if [ -f "$root/CLAUDE.md" ]; then
    printf '\n'
    render_claude_md "$mode" >"$WORK/claude.md"
    rule_body "$WORK/claude.md"
  else
    : >"$WORK/imported"
  fi
  render_always_on "$mode"
  render_scoped
  if [ -s "$WORK/blocks" ]; then
    printf '\n'
    cat "$WORK/blocks"
  fi
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

: >"$WORK/blocks"
if [ -f "$target" ]; then
  managed_blocks "$target" >"$WORK/blocks"
fi

render inline >"$WORK/AGENTS.md"
size="$(wc -c <"$WORK/AGENTS.md" | tr -d ' ')"
if [ "$size" -gt "$MAX_BYTES" ]; then
  render pointer >"$WORK/AGENTS.md"
  printf 'agents-md: inlined AGENTS.md would be %s bytes (> %s, Codex project_doc_max_bytes) — always-on rules written as pointers (%s bytes)\n' \
    "$size" "$MAX_BYTES" "$(wc -c <"$WORK/AGENTS.md" | tr -d ' ')" >&2
fi

if [ "$check" -eq 1 ]; then
  if [ ! -f "$target" ]; then
    printf 'agents-md: AGENTS.md missing — run agents-md.sh\n' >&2
    exit 1
  fi
  if ! agents_md_generated "$target"; then
    printf 'agents-md: AGENTS.md is hand-written (no GENERATED header) — move its content into CLAUDE.md or .claude/rules/, then run agents-md.sh --force\n' >&2
    exit 1
  fi
  without_managed_blocks "$target" >"$WORK/current.stripped"
  without_managed_blocks "$WORK/AGENTS.md" >"$WORK/generated.stripped"
  if ! cmp -s "$WORK/current.stripped" "$WORK/generated.stripped"; then
    printf 'agents-md: AGENTS.md is out of date with CLAUDE.md / .claude/rules — run agents-md.sh\n' >&2
    exit 1
  fi
  exit 0
fi

if [ -f "$target" ] && [ "$force" -eq 0 ] && ! agents_md_generated "$target"; then
  printf 'agents-md: AGENTS.md is hand-written (no GENERATED header) — move its content into CLAUDE.md or .claude/rules/ first, then rerun (--force overwrites it)\n' >&2
  exit 2
fi

if [ -f "$target" ] && cmp -s "$WORK/AGENTS.md" "$target"; then
  exit 0
fi
cp "$WORK/AGENTS.md" "$target"
printf 'AGENTS.md\n'
